### ISSUE TITLE
DevelopmentWorkflow is missing a lot of information and is not helpful.

### ISSUE THREAD

**Issue by VladimirAmiorkov** [Akylas/nativescript-image#6]
The workflow described [here](https://github.com/Akylas/nativescript-image/blob/master/DevelopmentWorkflow.md) for contributions to this repository is missing many of the details it should contain like:
- How to bind the local source code of the plugin and test it in side the demo application
- How to package the local version of the plugin in a tgz
- How to sync changes to the src folder so that the currently worked on demo app is synced.

Also it contains outdated command `npm run demo.ng.android` that is not found in the package.json located at the `src` directory.

**Comment by farfromrefug** [comment]
@VladimirAmiorkov Sorry i actually copied the one from ```nativescript-fresco``` but did not updated it enough.
Just for the context i don't use the same directory structure as others nativescript plugins because it creates a lot of issues. Especially :
- sources files (ts) and product files end up in the same place which is never good. When you ```npm link``` or use ```file:/../src``` you end up with a webpack installation which does not know what file to use. Already took me days to find bugs because of that.
- ```src``` folder contains a package.json which has dev dependencies which can create bad consequences when used with ```npm link``` or ```file:/../src```
- easier to clean when sources are separated from product.

Now all that being said it has a few issues that i still need to handle:
- ```tsc``` does not copy existing typings, thus the use of ```cpy```
- the package.json from ```plugin``` should be synced (without dev-deps) with the one from top
- the readme from top needs to be synced with the one from ```plugin``` to get the readme on npm

Will fix all now

**Comment by farfromrefug** [comment]
@VladimirAmiorkov changed the doc a bit. Can you look and tell me if it's ok with you?

**Comment by VladimirAmiorkov** [comment]
Yes now it is better. One thing that I personally find useful to have in a "Developer workflow" is also explain the steps required to manually build the plugins code so that it is ready for use (with symlink or npm link). Basically the above notes you have already mentioned I think that they are useful to have in a section in the DeveloperWorkflow.md so that anyone new to the repository can get the idea behind the current build process of the plugin's code. Feel free to close this issue.
