### ISSUE TITLE
Images don't load after creating and publishing Android App Bundle

### ISSUE THREAD

**Issue by VeeK727** [Akylas/nativescript-image#9]
### Which platform(s) does your issue occur on?
- Android
- Android Pie Tested 
- Real device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.3.2
- Cross-platform modules: 5.3.1
- Runtime(s): 5.3.1 both
- Plugin(s): 
```
"dependencies": {
    "nativescript-cardview": "3.1.1",
    "nativescript-carousel": "4.1.0",
    "nativescript-checkbox": "3.0.3",
    "nativescript-exit": "1.0.1",
    "nativescript-gif": "4.0.2",
    "nativescript-image": "2.1.3",
    "nativescript-loading-indicator": "2.4.0",
    "nativescript-material-icons": "1.0.3",
    "nativescript-permissions": "1.3.6",
    "nativescript-phone": "1.4.0",
    "nativescript-photoviewer": "2.1.1",
    "nativescript-plugin-firebase": "8.2.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-toasty": "1.3.0",
    "nativescript-ui-dataform": "4.0.0",
    "nativescript-ui-listview": "6.2.0",
    "nativescript-ui-sidedrawer": "6.0.0",
    "nativescript-youtubeplayer": "3.0.1",
    "tns-core-modules": "^5.3.1"
  }
```
### Please, tell us how to recreate the issue in as much detail as possible. 
Load an image from URL. Publish your app with Android App Bundle (.aab file) and test if image loads.

### Is there any code involved? 
```
<img:Img row="0" width="{{ width }}" height="{{ width }}" decodeWidth="{{ width }}" decodeHeight="{{ width }}" progressiveRenderingEnabled="true" src="{{ image }}" placeholderImageUri="~/images/loading.jpg" failureImageUri="~/images/loading.jpg" />
```
Works fine on local testing.

**Comment by farfromrefug** [comment]
You need to test your app in release. You can run your app on your device using ```tns run ios --release ...```. You can then see what's happening

**Comment by VeeK727** [comment]
I've tried that and it works. It just stops working when I generate the aab file and upload it to Play Store. Will it help if I add you to the internal test team of my app?

**Comment by farfromrefug** [comment]
No it won't really help. Look at your generated aab file and make sure the file is there, that it is in the right location ...
Can't really help more for now. I am 99,999% this has nothing to do with the plugin.

**Comment by VeeK727** [comment]
Of course I know where the aab file is, I uploaded it to the play store. Have you tried creating a bundle file and publishing it? Does it work fine?

**Comment by farfromrefug** [comment]
I am not asking you if you know where the aab file is. I am telling to make sure the image is inside the aab when you publish it. {N} running within aab is no different from apk.
I have created aab and have never seen any issues with image. However i am not sure if those apps were using local image like you do

**Comment by VeeK727** [comment]
I'm sorry if I didn't make it clear but I'm not using local images. They
are being loaded from the server.

**Comment by farfromrefug** [comment]
@VeeK727 your example shows local image loading so i thought...
Without any log i can't really help more. Sorry

**Comment by VeeK727** [comment]
The `src` attribute is dynamic and is loaded via the api. The placeholder image is local and it does load. Can you share your email or other contact so I can share my project with you privately?

**Comment by farfromrefug** [comment]
@VeeK727 see my profile

**Comment by mikloshumli** [comment]
this is my problem too. I tested with run and debug mode works fine but if make aab and upload to release then crash the app. Please help me what I doing this error. I have facebook pipeline error.

**Comment by farfromrefug** [comment]
@mikloshumli what is the facebook pipeline error?

**Comment by farfromrefug** [comment]
@mikloshumli @VeeK727 should be fixed in 2.1.4. Let me know

**Comment by ceht** [comment]
Same problem. In 2.1.4.
It works perfectly in testing but crashes with aab, and doesn't work with  `tns run android  --release ...`.
I'm developing my app with Angular. I've tested my app with `tns android run` and everything worked fine, the images loaded properly, I use both local and remote src for images and all load without problems, then I've built the aab with webpack, uglify and snapshot options enabled, that builds the project without problems (but throws some log output errors), but then I've create and published the Android version, download it from the app store and the app crashes. I have to say the app version I've downloaded from play store works fine at the begining, with the initial pages, but when I navigate to a page that loads an image with NSImg then it crashes. I have test other features and pages of my app (release version) that doesn't load any images and all work fine, so I'm almost certainly sure that when it crashes the error is related or cuased by nativescript-image.
*** Currently I'm trying to test it with `tns run android --release ...`  but that actually throw an error, I suspect that some changes in last versions of tns broke some typescript tasks since the error says it can't load some modules, (this also has disable me to use aot option when building aab) maybe that's related with the error because however the aab is built without problems I've also received the facebook pipeline errors.
These are the versions I'm using:

{
  "nativescript": {
    "id": {
      "android": "my.app"
    },
    "tns-ios": {
      "version": "5.4.1"
    },
    "tns-android": {
      "version": "5.4.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "email-validator": "^2.0.4",
    "nativescript-angular": "^7.2.4",
    "nativescript-camera": "^4.3.0",
    "nativescript-cfalert-dialog": "^1.0.14",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-datetimepicker": "^1.1.0",
    "nativescript-fancyalert": "^3.0.6",
    "nativescript-feedback": "^1.3.9",
    "nativescript-filterable-listpicker": "^2.2.5",
    "nativescript-floatingactionbutton": "^5.0.0",
    "nativescript-geolocation": "^4.4.1",
    "nativescript-image": "^2.1.4",
    "nativescript-imagepicker": "^6.1.2",
    "nativescript-loading-indicator": "^2.5.2",
    "nativescript-local-notifications": "^3.1.2",
    "nativescript-secure-storage": "^2.3.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^6.3.2",
    "nativescript-ui-sidedrawer": "^6.0.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^5.4.2",
    "typescript": "^3.4.4",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^7.2.3",
    "@angular/compiler-cli": "8.0.0",
    "@nativescript/schematics": "^0.5.0",
    "@ngtools/webpack": "8.0.0",
    "jscrambler-webpack-plugin": "^5.3.5",
    "nativescript-dev-typescript": "^0.7.9",
    "nativescript-dev-webpack": "^0.24.1"
  },
  "readme": "NativeScript Application"
}


The facebook pipeline errrors when building aab:

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
(node:8185) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Skip com.facebook.animated.gif.GifFrame
        Error: java.lang.NullPointerException
Skip com.facebook.animated.gif.GifImage
        Error: java.lang.NullPointerException
Skip com.google.errorprone.annotations.IncompatibleModifiers
        Error: java.lang.NullPointerException
Project successfully built.

**Comment by VeeK727** [comment]
@ceht Just wanted to mention, I also receive those deprecation warnings in my app and have been receiving them pretty much since I started using nativescript and before using nativescript-image. 
```
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
(node:8185) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
I don't think these lines are related to facebook or nativescript-image. BTW why do you call it facebook pipeline error? I don't have any facebook related modules in my app and I don't see you having one either in the version list above.

**Comment by ceht** [comment]
Yeah, as you mention I've also been receiving almost all of them before using nativescript-image, I just copied all the warnings, but these ones are new ones:

Note: Recompile with -Xlint:deprecation for details.
Skip com.facebook.animated.gif.GifFrame
Skip com.facebook.animated.gif.GifImage
Skip com.google.errorprone.annotations.IncompatibleModifiers
I install some other plugins and update tns at the same time I install nativescript-image, so I'm not sure if all they are related to this plugin.
I just called it 'facebook errors' becasuse I saw @mikloshumli called it that way, (because this Skip com.facebook.animated.gif.GifImage) but I think they're related to fresco, but not sure. And yeah, I don't use any facebook related module in my app.

**Comment by VeeK727** [comment]
Okay. I'm not sure what exactly is a facebook pipeline error but these just seems like image/graphic assets that the app is not able to load/compile, hence skipping. 

Anyways the core issue definitely exists and needs to be addressed.

**Comment by farfromrefug** [comment]
guys did you remove the platform folder after updating the package? it should work. i tried here with success.

**Comment by ceht** [comment]
Solved! 😁
I finally had been able to use it properly. In the previous test I also cleaned the platform, now I deleted also the node_modules, and hooks folders and do npm prune. I also updated webpack with this [commands](https://docs.nativescript.org/releases/upgrade-instructions#upgrading-webpack). The app now works fine with both, ` tns run android --bundle --env.uglify --env.snapshot --release ...` and the released version from the app store that I built with `tns build android --bundle --env.uglify --env.snapshot --release ...` as a aab. Thank you @farfromrefug the plugin is awesome.
